// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var form, scrollio;
    scrollio = function(target, speed) {
      return $("html, body").animate({
        scrollTop: $(target).offset().top
      }, speed);
    };
    $(window).scroll(function() {
      var scroll;
      return scroll = $(window).scrollTop();
    });
    form = $("#subscribe");
    return form.submit(function(e) {
      e.preventDefault();
      form.removeClass('shake');
      return $.getJSON(this.action + "?callback=?", $(this).serialize(), function(data) {
        var invalidSubmit, justSubmitted, messageNode, successEntry;
        messageNode = $('.message');
        if (data.Status === 400) {
          invalidSubmit = $("" + form + " input[type=email]").val();
          form.addClass('shake');
          return messageNode.html("Sorry, something went wrong with the email address " + invalidSubmit + ".");
        } else {
          justSubmitted = $("" + form + " input[type=email]").val();
          successEntry = "Thank You!";
          return messageNode.html("Welcome to the mailing list!");
        }
      });
    });
  });

}).call(this);
