// Generated by CoffeeScript 1.3.3

$(function() {
  return $('a').click(function(e) {
    e.preventDefault();
    $('ul').find('.flipInX').removeClass('flipInX');
    return $(this).parent('li').addClass('flipInX');
  });
});
